services:
  phpfpm:
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_POST_MAX_SIZE=10M
      - PHP_UPLOAD_MAX_FILESIZE=10M
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - ../../shared/settings.local.php:/app/web/sites/default/settings.local.php

  nginx:
    environment:
      - NGINX_MAX_BODY_SIZE=12M
    volumes:
      - ../../shared/files:/app/web/sites/default/files
