<?php

$color_schemes=[
    'default' => [
      'title' => t('Default'),
      'colors' => [
      'Primary Color' => '#2055e4',
      'Secondary Color' => '#f37272',
      ],
    ],
    'set_1' => [
      'title' => t('Color Set 1'),
      'colors' => [
      'Primary Color' =>'#1e6ae1',
      'Secondary Color' => '#1ee196',
      ],
    ],
    'set_2' => [
      'title' => t('Color Set 2'),
      'colors' => [
      'Primary Color' => '#1ecbe1',
      'Secondary Color' => '#e1341e',
      ],
    ],
    'set_3' => [
      'title' => t('Color Set 3'),
      'colors' => [
      'Primary Color' => '#ef2936',
      'Secondary Color' => '#ffbf00',
      ],
    ],
    'set_4' => [
      'title' => t('Color Set 4'),
      'colors' => [
      'Primary Color' => '#153156',
      'Secondary Color' => '#1ac6ff',
      ],
    ],
    'set_5' => [
      'title' => t('Color Set 5'),
      'colors' => [
      'Primary Color' => '#014b5f',
      'Secondary Color' => '#d2a679',
      ],
    ],
    'set_6' => [
      'title' => t('Color Set 6'),
      'colors' => [
      'Primary Color' => '#711c82',
      'Secondary Color' => '#d2a679',
      ],
    ],
    'set_7' => [
      'title' => t('Color Set 7'),
      'colors' => [
      'Primary Color' => '#111',
      'Secondary Color' => '#23a7ad',
      ],
    ],
    'set_8' => [
      'title' => t('Color Set 8'),
      'colors' => [
      'Primary Color' => '#e6565e',
      'Secondary Color' => '#24cd8c',
      ],
    ],
    'set_9' => [
      'title' => t('Color Set 9'),
      'colors' => [
      'Primary Color' => '#452e65',
      'Secondary Color' => '#153156',
      ],
    ],
];